[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyRobotiqGripper"
version = "1.0.0"
authors = [
  { name="Benoit CASTETS", email="opensourceeng@gmail.com" },
]
description = "Python Driver for Robotiq Grippers via Modbus RTU"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/castetsb/pyRobotiqGripper"
Issues = "https://github.com/castetsb/pyRobotiqGripper/issues"